version: "3.9"
services:
  micontainer: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    links: 
      - monguito
    volumes: 
      - .:/home/app #mi ruta actual es la que tiene que ser montada en el volumen:ruta destino dentro del container
  monguito: 
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=del
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: